repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-builtin-literals
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-xml
    - id: debug-statements
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: file-contents-sorter
    - id: forbid-new-submodules
    - id: mixed-line-ending
    - id: no-commit-to-branch
    - id: pretty-format-json
    - id: requirements-txt-fixer
    - id: trailing-whitespace
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.4
    hooks:
    - id: shell-lint
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    - id: pylint